name: Docker Publish

on:
  push:
    branches: [ "main" ] # Or your default branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Needed to push to Docker Hub

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }} # Store your Docker Hub username as a secret
        password: ${{ secrets.DOCKERHUB_TOKEN }}   # Store your Docker Hub token as a secret

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-site:latest,${{ secrets.DOCKERHUB_USERNAME }}/portfolio-site:${{ github.sha }} # Replace 'portfolio-site' if needed
        cache-from: type=gha
        cache-to: type=gha,mode=max